"""Inicializar interaccion con elementos

Revision ID: b85a888d3ef8
Revises: 
Create Date: 2025-03-24 23:30:44.873779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b85a888d3ef8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elemento', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('usuario_cookie', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interaccion')
    # ### end Alembic commands ###
